#!/usr/bin/env bash

export APP="cloud-run-fastapi"
export REPOSITORY="chugai"
export REGION="us-central1"
export PROJECT_ID="aiml-play"
export IMAGE_VER="0.1.0"
export IMAGE="${APP}:${IMAGE_VER}"
export IMAGE_PATH="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}"
export GOOGLE_APPLICATION_CREDENTIALS="/home/shyamg/dev/keys/aiml-play-557204fa5644.json"
export PROJECT_NUMBER="$(gcloud projects describe ${PROJECT_ID} --format='value(projectNumber)')"
export SERVICE_ACCOUNT="token-creator"
export SRC_DIR="."
export CB_YAML="${SRC_DIR}/cloudbuild.yaml"
export PORT="8080"